/**
 * NotificationAlarmScreen — shown when the user taps a scheduled push
 * notification for prayer or devotions.
 *
 * The server auto-generates the content before sending the push, so by the
 * time this screen appears the entry already exists in Supabase.  The user
 * sees the content immediately — they do not need to tap "Generate" anything.
 *
 * Tap "Open in Living Olive" (or the swipe-up button) to dismiss and land
 * on the Prayer or Devotions screen where the full history is visible.
 */

import React, { useEffect, useState } from "react";
import {
  View,
  Text,
  ScrollView,
  Pressable,
  StyleSheet,
  ActivityIndicator,
  Dimensions,
  Platform,
} from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import { useNavigation, useRoute, RouteProp } from "@react-navigation/native";
import type { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { supabase } from "../lib/supabase";
import { colors, radii, spacing, typography, shadows } from "../theme/theme";
import type { RootStackParamList } from "../navigation/AppNavigator";

const { width: SCREEN_W } = Dimensions.get("window");

type AlarmRoute = RouteProp<RootStackParamList, "NotificationAlarm">;
type Nav = NativeStackNavigationProp<RootStackParamList>;

// ── Clock display ─────────────────────────────────────────────────────────────
function ClockDisplay() {
  const [time, setTime] = useState(() => {
    const d = new Date();
    const h = d.getHours();
    const m = d.getMinutes().toString().padStart(2, "0");
    const ampm = h >= 12 ? "PM" : "AM";
    const h12 = h % 12 || 12;
    return `${h12}:${m} ${ampm}`;
  });

  useEffect(() => {
    const id = setInterval(() => {
      const d = new Date();
      const h = d.getHours();
      const m = d.getMinutes().toString().padStart(2, "0");
      const ampm = h >= 12 ? "PM" : "AM";
      const h12 = h % 12 || 12;
      setTime(`${h12}:${m} ${ampm}`);
    }, 30000);
    return () => clearInterval(id);
  }, []);

  return <Text style={styles.clock}>{time}</Text>;
}

// ── Prayer point alarm ─────────────────────────────────────────────────────────
type PrayerEntry = {
  id: string;
  title: string;
  prayer_text: string;
  scripture_reference: string | null;
};

function PrayerAlarmContent({ entryId }: { entryId: string }) {
  const [entries, setEntries] = useState<PrayerEntry[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      // If we have a specific entryId, load that entry's plan_id and fetch all
      // entries from the same plan (the batch generated by the cron job).
      const { data: pivot } = await supabase
        .from("prayer_entries")
        .select("plan_id")
        .eq("id", entryId)
        .single();

      if (pivot?.plan_id) {
        const { data } = await supabase
          .from("prayer_entries")
          .select("id, title, prayer_text, scripture_reference")
          .eq("plan_id", pivot.plan_id)
          .order("created_at", { ascending: true })
          .limit(10);
        setEntries(data ?? []);
      } else {
        // Fallback: just load this one entry
        const { data } = await supabase
          .from("prayer_entries")
          .select("id, title, prayer_text, scripture_reference")
          .eq("id", entryId)
          .single();
        if (data) setEntries([data]);
      }
      setLoading(false);
    })();
  }, [entryId]);

  if (loading) return <ActivityIndicator color={colors.gold} style={{ marginTop: spacing.xl }} />;

  return (
    <>
      {entries.map((e, i) => (
        <View key={e.id} style={styles.prayerCard}>
          <Text style={styles.prayerCardTitle}>{e.title}</Text>
          <Text style={styles.prayerCardBody}>{e.prayer_text}</Text>
          {e.scripture_reference ? (
            <View style={styles.refRow}>
              <Text style={styles.refIcon}>✦</Text>
              <Text style={styles.refText}>{e.scripture_reference}</Text>
            </View>
          ) : null}
        </View>
      ))}
    </>
  );
}

// ── Devotion alarm ─────────────────────────────────────────────────────────────
type DevotionEntry = {
  id: string;
  title: string;
  scripture_reference: string | null;
  scripture_text: string | null;
  body: string;
  closing_prayer: string | null;
};

function DevotionAlarmContent({ entryId }: { entryId: string }) {
  const [entry, setEntry] = useState<DevotionEntry | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      const { data } = await supabase
        .from("devotion_entries")
        .select("id, title, scripture_reference, scripture_text, body, closing_prayer")
        .eq("id", entryId)
        .single();
      setEntry(data ?? null);
      setLoading(false);
    })();
  }, [entryId]);

  if (loading) return <ActivityIndicator color={colors.gold} style={{ marginTop: spacing.xl }} />;
  if (!entry) return <Text style={styles.emptyText}>Could not load devotion — open the app to view it.</Text>;

  return (
    <View style={styles.devotionCard}>
      {entry.scripture_reference ? (
        <View style={styles.scriptureTag}>
          <Text style={styles.scriptureTagText}>{entry.scripture_reference}</Text>
        </View>
      ) : null}
      <Text style={styles.devotionTitle}>{entry.title}</Text>
      {entry.scripture_text ? (
        <View style={styles.scriptureQuote}>
          <View style={styles.quoteBar} />
          <Text style={styles.scriptureText}>{entry.scripture_text}</Text>
        </View>
      ) : null}
      <Text style={styles.devotionBody} numberOfLines={8}>{entry.body}</Text>
      {entry.closing_prayer ? (
        <View style={styles.prayerWrap}>
          <Text style={styles.prayerLabel}>CLOSING PRAYER</Text>
          <Text style={styles.prayerText}>{entry.closing_prayer}</Text>
        </View>
      ) : null}
    </View>
  );
}

// ── Main alarm screen ─────────────────────────────────────────────────────────
export default function NotificationAlarmScreen() {
  const navigation = useNavigation<Nav>();
  const route = useRoute<AlarmRoute>();
  const { type, entryId, goal, desires, prayerType, previewText } = route.params;

  function dismiss() {
    if (type === "devotion") {
      navigation.replace("Devotions");
    } else {
      navigation.replace("Prayer");
    }
  }

  const isPrayer = type === "prayer";
  const gradientColors: [string, string, string] = isPrayer
    ? ["#2A3820", "#3E4A2F", "#5B6B45"]
    : ["#5B4010", "#8A6A10", "#C9A227"];

  const labelIcon = isPrayer ? "🙏" : "🌿";
  const labelText = isPrayer ? "PRAYER POINTS READY" : "DEVOTION READY";
  const ctaText = isPrayer ? "View Prayer Points →" : "Open Devotion →";

  return (
    <View style={styles.root}>
      <LinearGradient colors={gradientColors} style={styles.header}>
        <Text style={styles.alarmLabel}>{labelIcon} {labelText}</Text>
        <ClockDisplay />
        <Text style={styles.headerSub}>
          {isPrayer
            ? `Your ${prayerType ?? "prayer"} points have been prepared for you`
            : `Your devotion on "${goal ?? "your goal"}" is ready`}
        </Text>
      </LinearGradient>

      <ScrollView style={styles.scroll} contentContainerStyle={styles.scrollContent}>
        {entryId ? (
          isPrayer
            ? <PrayerAlarmContent entryId={entryId} />
            : <DevotionAlarmContent entryId={entryId} />
        ) : (
          <View style={styles.previewCard}>
            <Text style={styles.previewText}>{previewText ?? "Open the app to read your content."}</Text>
          </View>
        )}

        <View style={styles.ctaSection}>
          <Pressable
            style={({ pressed }) => [styles.ctaBtn, pressed && { opacity: 0.85 }]}
            onPress={dismiss}
          >
            <LinearGradient
              colors={gradientColors}
              start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }}
              style={styles.ctaBtnGrad}
            >
              <Text style={styles.ctaBtnText}>{ctaText}</Text>
            </LinearGradient>
          </Pressable>
          <Text style={styles.ctaHint}>Tap to go to {isPrayer ? "Prayer" : "Devotions"} screen</Text>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.parchment },
  header: {
    paddingTop: Platform.OS === "ios" ? 56 : 32,
    paddingBottom: spacing.xl,
    paddingHorizontal: spacing.lg,
    alignItems: "center",
  },
  alarmLabel: {
    ...typography.micro,
    color: "rgba(255,255,255,0.7)",
    letterSpacing: 2,
    marginBottom: spacing.sm,
  },
  clock: {
    fontSize: 56,
    fontWeight: "700",
    color: colors.white,
    letterSpacing: -1,
    marginBottom: spacing.sm,
  },
  headerSub: {
    ...typography.caption,
    color: "rgba(255,255,255,0.7)",
    textAlign: "center",
    maxWidth: SCREEN_W - 64,
  },
  scroll: { flex: 1 },
  scrollContent: { padding: spacing.lg, paddingBottom: spacing.xxxl },
  prayerCard: {
    backgroundColor: colors.white,
    borderRadius: radii.lg,
    padding: spacing.md,
    marginBottom: spacing.md,
    ...shadows.subtle,
  },
  prayerCardTitle: { ...typography.subtitle, color: colors.oliveDark, marginBottom: spacing.sm },
  prayerCardBody: { ...typography.bodySmall, color: colors.ink, lineHeight: 22 },
  refRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginTop: spacing.sm,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.parchmentMid,
  },
  refIcon: { color: colors.gold, fontSize: 10 },
  refText: { ...typography.caption, color: colors.terracotta, fontStyle: "italic" },
  devotionCard: {
    backgroundColor: colors.white,
    borderRadius: radii.lg,
    padding: spacing.md,
    marginBottom: spacing.md,
    ...shadows.subtle,
  },
  scriptureTag: {
    alignSelf: "flex-start",
    backgroundColor: colors.terracotta,
    borderRadius: radii.pill,
    paddingVertical: 3,
    paddingHorizontal: spacing.sm,
    marginBottom: spacing.sm,
  },
  scriptureTagText: { ...typography.micro, color: colors.white, letterSpacing: 0.5 },
  devotionTitle: { ...typography.subtitle, color: colors.oliveDark, marginBottom: spacing.sm },
  scriptureQuote: {
    flexDirection: "row",
    gap: spacing.sm,
    backgroundColor: colors.parchment,
    borderRadius: radii.sm,
    padding: spacing.sm,
    marginBottom: spacing.sm,
  },
  quoteBar: { width: 3, borderRadius: 2, backgroundColor: colors.gold },
  scriptureText: {
    ...typography.bodySmall,
    color: colors.inkSoft,
    flex: 1,
    fontStyle: "italic",
    lineHeight: 20,
  },
  devotionBody: { ...typography.bodySmall, color: colors.ink, lineHeight: 22 },
  prayerWrap: {
    marginTop: spacing.sm,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.parchmentMid,
  },
  prayerLabel: { ...typography.micro, color: colors.inkFaint, letterSpacing: 2, marginBottom: 4 },
  prayerText: { ...typography.bodySmall, color: colors.inkSoft, fontStyle: "italic", lineHeight: 20 },
  previewCard: {
    backgroundColor: colors.white,
    borderRadius: radii.lg,
    padding: spacing.lg,
    marginBottom: spacing.md,
    ...shadows.subtle,
  },
  previewText: { ...typography.body, color: colors.ink, lineHeight: 26 },
  emptyText: { ...typography.bodySmall, color: colors.inkFaint, textAlign: "center", padding: spacing.xl },
  ctaSection: { marginTop: spacing.lg, alignItems: "center" },
  ctaBtn: { width: "100%", borderRadius: radii.md, overflow: "hidden", ...shadows.card },
  ctaBtnGrad: {
    paddingVertical: spacing.md + 2,
    alignItems: "center",
    justifyContent: "center",
  },
  ctaBtnText: { color: colors.white, fontWeight: "700", fontSize: 16, letterSpacing: 0.2 },
  ctaHint: { ...typography.caption, color: colors.inkFaint, marginTop: spacing.sm },
});
